################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.c \
../libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.c 

OBJS += \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.o \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.o 

C_DEPS += \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_adc_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_can.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cec.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_crc_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dac_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dcmi_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dfsdm.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma2d.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dsi.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_eth.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hash_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_hcd.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2s.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_irda.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_iwdg.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_jpeg.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_lptim.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_ltdc_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mdios.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_mmc.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nand.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_nor.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pcd_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_qspi.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rng.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rtc_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sai_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sd.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sdram.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smartcard_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_smbus.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spdifrx.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_spi_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_sram.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_tim_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_uart_ex.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_usart.d \
./libraries/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_wwdg.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/STM32F7xx_HAL_Driver/Src/%.o: ../libraries/STM32F7xx_HAL_Driver/Src/%.c
	arm-none-eabi-gcc -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DDEBUG -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\drivers" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\libraries" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\libraries\CMSIS\Device\ST\STM32F7xx\Include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\libraries\CMSIS\Include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\libraries\STM32F7xx_HAL_Driver\Inc" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\at_device-v2.0.2\class\ec20" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\at_device-v2.0.2\inc" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\dht11-latest" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\ports\fal" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\ports\rtthread" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\ports\ssl" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\certs" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\dev_model\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\mqtt\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\ota\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\sdk-impl" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\shadow\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\packages\ucloud_iot_sdk-latest\uiot\utils" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\drivers\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\drivers\sensors" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\finsh" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\libc\compilers\newlib" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\at\at_socket" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\at\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\netdev\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\sal_socket\impl" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\sal_socket\include\socket\sys_socket" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\sal_socket\include\socket" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\components\net\sal_socket\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\include" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\libcpu\arm\common" -I"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rt-thread\libcpu\arm\cortex-m7" -include"D:\software\RT-ThreadStudio\workspace\rtthread_uiot_test\rtconfig_preinc.h" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

